export enum TYPEEMPLOYMENT {
  GET_TYPEEMPLOYMENT_REQUEST = 'GET_TYPEEMPLOYMENT_REQUEST',
  GET_TYPEEMPLOYMENT_PENDING = 'GET_TYPEEMPLOYMENT_PENDING',
  GET_TYPEEMPLOYMENT_SUCCESS = 'GET_TYPEEMPLOYMENT_SUCCESS',
  GET_TYPEEMPLOYMENT_FAILD = 'GET_TYPEEMPLOYMENT_FAILD',
}
