export enum AUTH {
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_PENDING = 'SIGN_UP_PENDING',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',

  VERIFY_REQUEST = 'VERIFY_REQUEST',
  VERIFY_PENDING = 'VERIFY_PENDING',
  VERIFY_SUCCESS = 'VERIFY_SUCCESS',
  VERIFY_FAILED = 'VERIFY_FAILED',

  SIGN_IN = 'SIGN_IN',
  SIGN_IN_PENDING = 'SIGN_IN_PENDING',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED = 'SIGN_IN_FAILED',

  SIGN_OUT = 'SIGN_OUT',
  SET_TOKEN = 'SET_TOKEN',
}
