export enum USER {
  GET_USER_REQUEST = 'GET_USER_REQUEST',
  GET_USER_PENDING = 'GET_USER_PENDING',
  GET_USER_SUCCESS = 'GET_USER_SUCCESS',
  GET_USER_FAILD = 'GET_USER_FAILD',

  POST_USER_AVATAR_REQUEST = 'POST_USER_AVATAR_REQUEST',
  POST_USER_AVATAR_SUCCESS = 'POST_USER_AVATAR_SUCCESS',
  POST_USER_AVATAR_FAILD = 'POST_USER_AVATAR_FAILD',

  GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS',
  GET_USER_AVATAR_FAILD = 'GET_USER_AVATAR_FAILD',

  UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST',
  UPDATE_USER_PENDING = 'UPDATE_USER_PENDING',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILD = 'UPDATE_USER_FAILD',
}
