export enum SERVICE {
  GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST',
  GET_SERVICES_PENDING = 'GET_SERVICES_PENDING',
  GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS',
  GET_SERVICES_FAILD = 'GET_SERVICES_FAILD',
}
